version: "3"
services:
  py2:
    # replace username/repo:tag with your name and image details
    image: 001-py2-node:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  py3:
    # replace username/repo:tag with your name and image details
    image: 002-py3-node:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4040:80"
    networks:
      - webnet
networks:
  webnet: